## Seed riders for new event

This Notebook is to utilize the ranked riders data and load a list of participating riders in a new event.
The riders in the new event will get seeded if they have been participating in the competition from last year's Vintercupen.

In [2]:
import os
import pandas as pd

## Load previous ranked data

In [3]:
file_path = 'ranked/ranked.csv'

# Read the CSV file into a DataFrame
ranked_dataframe = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(ranked_dataframe.head())

                       Namn         Klubb     #         Klass  \
0             Albin Elowson   FMCK Skövde     1          Elit
1  Simon Hopander Ankarhake  Nyköpings MS   304  Motion 16-29
2            Sören Fransson      Kinds MK  1236  Motion 50-59
3            Niklas Persson  Karlskoga EK    28        Senior
4            Rikard Hansson      Tibro MK    73        Senior

   Rank FMK Skövde  Rank Tidaholms MK  Rank Töreboda MK  Rank Tibro MK  \
0            133.0                NaN               1.0            NaN
1            189.0                NaN               NaN            NaN
2              NaN                1.0               NaN            NaN
3              NaN                NaN               2.0            NaN
4              NaN                NaN               3.0            NaN

   Rank Carlsborgs MK  Rank Falköpings MK  AvgRank
0                 NaN                 NaN      1.0
1                 NaN                 1.0      1.0
2               161.0                 NaN      1.0
3                 NaN                 NaN      2.0
4                 2.0                 NaN      2.0

## load participants for an upcoming event.

In [4]:
file_path = 'unseeded/unseeded.csv'

# Read the CSV file into a DataFrame with the second row as column names
unseeded_dataframe = pd.read_csv(file_path, encoding='cp1252', header=0)

# Display the first few rows of the DataFrame
print(unseeded_dataframe.head(-10))

    Tidaholms MK  2024     #                         Namn               Klubb  \
0            NaN   NaN   900                Hans Torsborn      Ulricehamns MK
1            NaN   NaN   902               Peter Berggren       BMK Uddevalla
2            NaN   NaN   903              Björn Bäckström              MK Ran
3            NaN   NaN   905                Per Norlander         Kullings MS
4            NaN   NaN   906  Anders Billestedt Andersson     Stenungsunds MS
5            NaN   NaN   908          Johan Alexandersson           Götene MK
6            NaN   NaN   912          Lars-Olof Lindström          FMCK Borås
7            NaN   NaN   913             Daniel Blomqvist         FMCK Skövde
8            NaN   NaN   914             Niklas Utterberg     Norrahammars MK
9            NaN   NaN   915               Martin Jonsson         Töreboda MK
10           NaN   NaN   917             Fredrik Hassesjö         Kullings MS
11           NaN   NaN   920         Christoffer Johnsson        Hisingens MK
12           NaN   NaN   921              Mattias Roslund  Försvarsmaktens EK
13           NaN   NaN   922                Mikael Sahlin      Lidköpings MCK
14           NaN   NaN   924           Sebastian Carlsson        SMK Vadstena
15           NaN   NaN   927               Mikael Dalåsen     SMK Trollhättan
16           NaN   NaN   929             Daniel Lundqvist         Töreboda MK
17           NaN   NaN   931                 Andreas Leth       Älvbygdens MK
18           NaN   NaN   934               Johan Karlsson       Älvbygdens MK
19           NaN   NaN   937                 David Rudhem      Lidköpings MCK
20           NaN   NaN   945             Markus Björklund              Hjo MK
21           NaN   NaN   962              Jonas Bergqvist            Skene MS
22           NaN   NaN   966              Jimmy Andersson     Stenungsunds MS
23           NaN   NaN   971             Jonas Gustafsson           Götene MK
24           NaN   NaN   973         Ola Daniel Strandvad              Viking
25           NaN   NaN   974               Jonas Svensson       Hallsbergs MK
26           NaN   NaN   978                 Kim Dubriang         Limhamns MK
27           NaN   NaN   985              Joakim Ericsson         Töreboda MK
28           NaN   NaN   990               Johan Kjellson         FMCK Skövde
29           NaN   NaN   998             Andreas Sandberg          FMCK Borås
30           NaN   NaN   999              Johan Törnqvist         FMCK Skövde
31           NaN   NaN  1006           Anton Bernhardsson        Kortedala MK
32           NaN   NaN   911                 Robert Ahlin       Falköpings MK
33           NaN   NaN   501           Robert Hjalmarsson          MK Pionjär
34           NaN   NaN   502                   Marwin Wik            Skene MS
35           NaN   NaN   503          Christopher Skansen            Kinds MK
36           NaN   NaN   504              Christer Strand            Tibro MK
37           NaN   NaN   505                  Viktor Blom            Skene MS
38           NaN   NaN   506              Robert Stafsing         Varbergs MK
39           NaN   NaN   508                Maria Thomsen          FMCK Borås
40           NaN   NaN   509               Hugo Lindström          FMCK Borås
41           NaN   NaN   510             Simon Gustafsson       Älvbygdens MK
42           NaN   NaN   511                  Dennis Ring          FMCK Borås
43           NaN   NaN   513                 Niklas Kedén              Hjo MK
44           NaN   NaN   517            Patric Gustafsson        Huskvarna MK
45           NaN   NaN   530                Patrik Olsson     Lilla Edets MCK
46           NaN   NaN   547              Felix Johansson            Kinds MK
47           NaN   NaN   550              Eric Gustafsson        SMK Vingåker
48           NaN   NaN   556             Tommy Gustafsson        Huskvarna MK
49           NaN   NaN   585          Ludvig Bernhardsson        Kortedala MK
50           NaN   NaN   590               Tobias Hagelin          FMCK Borås
51           NaN   NaN   594                 Anton Torgin          Donkelo RK
52           NaN   NaN   622        Oscar Kalliomäki Berg     Lilla Edets MCK
53           NaN   NaN   757               Simon Karlsson     Stenungsunds MS
54           NaN   NaN   102                   Liam Qvist          Åbågen MCK
55           NaN   NaN   103              Anton Magnusson     Norrahammars MK

    Unnamed: 5
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
29         NaN
30         NaN
31         NaN
32         NaN
33         NaN
34         NaN
35         NaN
36         NaN
37         NaN
38         NaN
39         NaN
40         NaN
41         NaN
42         NaN
43         NaN
44         NaN
45         NaN
46         NaN
47         NaN
48         NaN
49         NaN
50         NaN
51         NaN
52         NaN
53         NaN
54         NaN
55         NaN

In [5]:
# Merge or lookup operation to find the AvgRank from ranked_dataframe for each row in unseeded_dataframe
seeded_df = unseeded_dataframe.merge(
    ranked_dataframe[['Namn', 'Klubb', 'AvgRank']],  # Selecting necessary columns from ranked_dataframe
    on=['Namn', 'Klubb'],  # Merging on 'Namn' and 'Klubb' columns
    how='left'  # Perform a left join to keep all rows from unseeded_dataframe
)

# Drop the 'Unnamed: 5' column if it exists
if 'Unnamed: 5' in seeded_df.columns:
    seeded_df.drop(columns=['Unnamed: 5'], inplace=True)

# Rename the 'AvgRank' column to 'Seeding'
seeded_df.rename(columns={'AvgRank': 'Seeding'}, inplace=True)

# Find the maximum AvgRank from ranked_dataframe
max_avg_rank = ranked_dataframe['AvgRank'].max()

# Fill missing Seeding values with the maximum AvgRank plus 1
seeded_df['Seeding'].fillna(max_avg_rank + 1, inplace=True)

# Sort by Seeding column
seeded_df = seeded_df.sort_values(by='Seeding')

seeded_df.head(-10)

,Tidaholms MK,2024,#,Namn,Klubb,Seeding
57,NaN,NaN,106,Hampus Andersson,Tibro MK,24.750000
61,NaN,NaN,141,William Brehag Von Haugwitz,Carlsborgs MK,36.000000
46,NaN,NaN,547,Felix Johansson,Kinds MK,78.000000
54,NaN,NaN,102,Liam Qvist,Åbågen MCK,81.750000
0,NaN,NaN,900,Hans Torsborn,Ulricehamns MK,82.500000
21,NaN,NaN,962,Jonas Bergqvist,Skene MS,90.000000
14,NaN,NaN,924,Sebastian Carlsson,SMK Vadstena,94.000000
27,NaN,NaN,985,Joakim Ericsson,Töreboda MK,94.250000
2,NaN,NaN,903,Björn Bäckström,MK Ran,102.000000
45,NaN,NaN,530,Patrik Olsson,Lilla Edets MCK,113.000000
36,NaN,NaN,504,Christer Strand,Tibro MK,115.000000
18,NaN,NaN,934,Johan Karlsson,Älvbygdens MK,118.333333
55,NaN,NaN,103,Anton Magnusson,Norrahammars MK,128.666667
6,NaN,NaN,912,Lars-Olof Lindström,FMCK Borås,131.000000
16,NaN,NaN,929,Daniel Lundqvist,Töreboda MK,131.333333
48,NaN,NaN,556,Tommy Gustafsson,Huskvarna MK,138.500000
4,NaN,NaN,906,Anders Billestedt Andersson,Stenungsunds MS,139.666667
42,NaN,NaN,511,Dennis Ring,FMCK Borås,152.666667
31,NaN,NaN,1006,Anton Bernhardsson,Kortedala MK,154.000000
47,NaN,NaN,550,Eric Gustafsson,SMK Vingåker,158.000000
40,NaN,NaN,509,Hugo Lindström,FMCK Borås,160.500000
25,NaN,NaN,974,Jonas Svensson,Hallsbergs MK,165.000000
32,NaN,NaN,911,Robert Ahlin,Falköpings MK,171.500000
44,NaN,NaN,517,Patric Gustafsson,Huskvarna MK,181.750000
35,NaN,NaN,503,Christopher Skansen,Kinds MK,187.000000
59,NaN,NaN,120,Albin Glansén,Tidaholms MK,188.000000
58,NaN,NaN,113,Benjamin Bengtsson,Falköpings MK,213.000000
8,NaN,NaN,914,Niklas Utterberg,Norrahammars MK,213.000000
28,NaN,NaN,990,Johan Kjellson,FMCK Skövde,221.500000
1,NaN,NaN,902,Peter Berggren,BMK Uddevalla,232.500000
23,NaN,NaN,971,Jonas Gustafsson,Götene MK,233.000000
11,NaN,NaN,920,Christoffer Johnsson,Hisingens MK,234.750000
7,NaN,NaN,913,Daniel Blomqvist,FMCK Skövde,238.000000
41,NaN,NaN,510,Simon Gustafsson,Älvbygdens MK,238.750000
56,NaN,NaN,104,Lisa Nyqvist,Stenungsunds MS,241.500000
9,NaN,NaN,915,Martin Jonsson,Töreboda MK,246.750000
43,NaN,NaN,513,Niklas Kedén,Hjo MK,257.000000
39,NaN,NaN,508,Maria Thomsen,FMCK Borås,261.666667
60,NaN,NaN,121,William Larsson,FMCK Skövde,275.000000
30,NaN,NaN,999,Johan Törnqvist,FMCK Skövde,277.750000
50,NaN,NaN,590,Tobias Hagelin,FMCK Borås,295.250000
13,NaN,NaN,922,Mikael Sahlin,Lidköpings MCK,303.000000
34,NaN,NaN,502,Marwin Wik,Skene MS,304.333333
5,NaN,NaN,908,Johan Alexandersson,Götene MK,307.000000
51,NaN,NaN,594,Anton Torgin,Donkelo RK,310.000000
29,NaN,NaN,998,Andreas Sandberg,FMCK Borås,319.000000
49,NaN,NaN,585,Ludvig Bernhardsson,Kortedala MK,323.000000
65,NaN,NaN,199,William Blom,Skene MS,328.666667
20,NaN,NaN,945,Markus Björklund,Hjo MK,444.000000
24,NaN,NaN,973,Ola Daniel Strandvad,Viking,444.000000
62,NaN,NaN,163,Erik Frisagård,Getinge MK,444.000000
63,NaN,NaN,176,Leo Revelj,BMK Uddevalla,444.000000
3,NaN,NaN,905,Per Norlander,Kullings MS,444.000000
26,NaN,NaN,978,Kim Dubriang,Limhamns MK,444.000000
17,NaN,NaN,931,Andreas Leth,Älvbygdens MK,444.000000
52,NaN,NaN,622,Oscar Kalliomäki Berg,Lilla Edets MCK,444.000000

In [6]:
seeded_df['Seeding'] = seeded_df.reset_index(drop=True).index + 1

seeded_df.head(100)

,Tidaholms MK,2024,#,Namn,Klubb,Seeding
57,NaN,NaN,106,Hampus Andersson,Tibro MK,1
61,NaN,NaN,141,William Brehag Von Haugwitz,Carlsborgs MK,2
46,NaN,NaN,547,Felix Johansson,Kinds MK,3
54,NaN,NaN,102,Liam Qvist,Åbågen MCK,4
0,NaN,NaN,900,Hans Torsborn,Ulricehamns MK,5
...,...,...,...,...,...,...
15,NaN,NaN,927,Mikael Dalåsen,SMK Trollhättan,62
33,NaN,NaN,501,Robert Hjalmarsson,MK Pionjär,63
64,NaN,NaN,186,Felix Johansson,Skene MS,64
53,NaN,NaN,757,Simon Karlsson,Stenungsunds MS,65
19,NaN,NaN,937,David Rudhem,Lidköpings MCK,66

In [7]:
import datetime

folder_name = 'seeded'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)
    
# Get the current date and time
current_time = datetime.datetime.now().strftime("%Y-%m-%d_%H%M")

# Define the filename with the current timestamp
file_name = f"seeded/{current_time}.csv"

# Save the DataFrame to a CSV file
try:
    seeded_df.to_csv(file_name, index=False, encoding='cp1252')  # Windows-1252 encoding
    print(f"Ranked data saved successfully to '{file_name}'")
except Exception as e:
    print(f"Error saving ranked data: {e}")

Ranked data saved successfully to 'seeded/2023-12-18_2229.csv'